name: Drive Tool Test

on:
  push:
    branches: [ master, feature/drive-tool ]
  pull_request:
    branches: [ master, feature/drive-tool ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Setup Git
        run: |
          git config user.name philgiasson
          git config user.email philgiasson@users.noreply.github.com


      - name: Install rush
        run: |
          node common/scripts/install-run-rush.js install
          rush install

      - name: Test
        working-directory: ./test-apps/ui-test-app
        run: npm run test
