name: Drive Tool Test

on:
  push:
    branches: [ master, feature/drive-tool ]
  pull_request:
    branches: [ master, feature/drive-tool ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        working-directory: ./test-apps/ui-test-app
        run: |
          npm install -g rush
          rush install

      - name: Test
        working-directory: ./test-apps/ui-test-app
        run: npm run test
